// main.js - Vee frontend + assistant UI (trimmed)
(function(){
  function getData(){ return JSON.parse(localStorage.getItem('vee_data')||'null'); }
  function setData(d){ localStorage.setItem('vee_data', JSON.stringify(d)); }
  function ensure(){ if(getData()) return; setData({ users:[{id:1,username:'Vee',password:'411',accountNumber:'ADMIN001A',isAdmin:true,points:300,purchases:[],reads:0,history:[]}], sections:[{id:'terminal',name:'ترمكس',subsections:[{id:'basics',name:'اساسيات الترمكس',paid:false,price:0,content:'تعلم الأساسيات...'}]},{id:'whatsapp',name:'واتساب',subsections:[{id:'reverse',name:'نسخة عكس',paid:false,price:0,content:'نسخة عكس...'}]}], achievements:[{id:'a1',name:'قارئ مبتدئ',rule:{type:'reads',value:5}},{id:'a2',name:'مشتري 3',rule:{type:'purchases',value:3}}] }); }
  ensure();
  function toast(msg,t=2200){ const el=document.getElementById('toast'); if(!el) return; el.innerText=msg; el.classList.remove('hidden'); setTimeout(()=>el.classList.add('hidden'),t); }
  function genAcc(users){ const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'; let acc; do{ acc='12'+(100+Math.floor(Math.random()*900))+letters.charAt(Math.floor(Math.random()*letters.length)); }while(users.some(u=>u.accountNumber===acc)); return acc; }

  const lf=document.getElementById('loginForm');
  if(lf){ document.getElementById('openRegister').addEventListener('click', ()=> document.getElementById('registerModal').classList.remove('hidden')); document.getElementById('closeRegister').addEventListener('click', ()=> document.getElementById('registerModal').classList.add('hidden')); document.getElementById('registerForm').addEventListener('submit', function(e){ e.preventDefault(); const name=document.getElementById('regName').value.trim(); const pass=document.getElementById('regPass').value; const data=getData(); if(data.users.some(u=>u.username.toLowerCase()===name.toLowerCase())){ alert('اسم المستخدم موجود'); return; } const acc=genAcc(data.users); const nu={id:data.users.length+1,username:name,password:pass,accountNumber:acc,isAdmin:false,points:50,purchases:[],reads:0,history:[]}; data.users.push(nu); setData(data); localStorage.setItem('vee_session', JSON.stringify({id:nu.id})); toast('تم إنشاء الحساب وتسجيل الدخول'); setTimeout(()=> location.href='dashboard.html',700); }); lf.addEventListener('submit', function(e){ e.preventDefault(); const name=document.getElementById('loginUsername').value.trim(); const pass=document.getElementById('loginPassword').value; const data=getData(); const u=data.users.find(x=>x.username===name && x.password===pass); if(!u){ alert('بيانات تسجيل الدخول غير صحيحة'); return; } localStorage.setItem('vee_session', JSON.stringify({id:u.id})); toast('تم تسجيل الدخول'); setTimeout(()=> location.href = u.isAdmin ? 'admin.html' : 'dashboard.html',700); }); }

  if(location.pathname.endsWith('dashboard.html')){
    const sess=JSON.parse(localStorage.getItem('vee_session')||'null'); if(!sess) location.href='login.html'; const data=getData(); const user=data.users.find(u=>u.id===sess.id); if(!user){ localStorage.removeItem('vee_session'); location.href='login.html'; }
    document.getElementById('pName').innerText = user.username; document.getElementById('pAccount').innerText = user.accountNumber; document.getElementById('pPoints').innerText = (user.points||0)+' نقطة';
    const badges = document.getElementById('badges'); const history = document.getElementById('history');
    user.reads = user.reads || 0;
    const totalItems = data.sections.reduce((acc,s)=>acc+s.subsections.length,0);
    const completed = (user.purchases||[]).length + (user.reads||0);
    const pct = Math.min(100, Math.round((completed/totalItems)*100));
    document.getElementById('progressFill').style.width = pct+'%';
    badges.innerHTML=''; data.achievements.forEach(a=>{ let earned=false; if(a.rule.type==='reads' && user.reads>=a.rule.value) earned=true; if(a.rule.type==='purchases' && (user.purchases||[]).length>=a.rule.value) earned=true; const el=document.createElement('div'); el.className='badge'; el.innerText = (earned? '🏅 ':'') + a.name; badges.appendChild(el); });
    history.innerHTML=''; (user.purchases||[]).concat(user.history||[]).forEach(h=>{ const r=document.createElement('div'); r.innerText = h; history.appendChild(r); });
    document.getElementById('logoutBtn').addEventListener('click', ()=>{ localStorage.removeItem('vee_session'); toast('تم تسجيل الخروج'); setTimeout(()=> location.href='index.html',700); });
    document.getElementById('chatSend').addEventListener('click', async ()=>{ const msg = document.getElementById('chatInput').value.trim(); if(!msg) return; addChat('user', msg); document.getElementById('chatInput').value=''; try{ const reply = await askAI(msg); addChat('bot', reply); }catch(err){ addChat('bot','حدث خطأ في الاتصال بالمساعد'); console.error(err); } });
  }

  if(location.pathname.endsWith('store.html')){ const data=getData(); const sess=JSON.parse(localStorage.getItem('vee_session')||'null'); const user = sess? data.users.find(u=>u.id===sess.id):null; const area=document.getElementById('storeArea'); area.innerHTML=''; data.sections.forEach(sec=> sec.subsections.filter(s=>s.paid).forEach(sub=>{ const c=document.createElement('div'); c.className='card'; c.innerHTML = '<h4>'+sub.name+'</h4><div>'+sec.name+'</div><div>'+sub.price+' نقطة</div>'; const btn=document.createElement('button'); btn.className='btn primary'; btn.innerText = user ? 'شراء' : 'سجل للدفع'; btn.addEventListener('click', ()=>{ if(!user){ alert('سجل الدخول أولاً'); return; } if((user.points||0) < sub.price){ alert('نقاط غير كافية'); return; } if(confirm('شراء المحتوى؟')){ user.points=(user.points||0)-sub.price; user.purchases=(user.purchases||[]).concat([sec.id+'-'+sub.id]); user.history = (user.history||[]).concat(['اشتريت '+sub.name]); setData(data); toast('تم الشراء'); } }); c.appendChild(btn); area.appendChild(c); })); }

  if(location.pathname.endsWith('admin.html')){ const sess=JSON.parse(localStorage.getItem('vee_session')||'null'); if(!sess) location.href='login.html'; const data=getData(); const admin=data.users.find(u=>u.id===sess.id && u.isAdmin); if(!admin){ localStorage.removeItem('vee_session'); location.href='login.html'; } const content=document.getElementById('adminContent'); function render(panel){ if(panel==='dashboard'){ content.innerHTML = '<h3>لوحة الأدمن</h3><div class=\"grid\"><div class=\"card\">المستخدمين: '+data.users.length+'</div><div class=\"card\">الأقسام: '+data.sections.length+'</div></div>'; } if(panel==='sections'){ let html='<h3>الأقسام</h3>'; data.sections.forEach((sec,si)=>{ html += '<div class=\"card\"><strong>'+sec.name+'</strong>'; sec.subsections.forEach((sub,subi)=> html += '<div>'+sub.name+' '+(sub.paid?('('+sub.price+' نقطة)'):'')+' <button data-si=\"'+si+'\" data-sub=\"'+subi+'\" class=\"btn">تعديل</button></div>'); html += '<div class=\"row\"><button data-add=\"'+si+'\" class=\"btn success\">إضافة أداة</button></div></div>'; }); content.innerHTML = html; content.querySelectorAll('button[data-add]').forEach(b=> b.addEventListener('click', e=> openTool({si:parseInt(e.target.getAttribute('data-add'))}))); content.querySelectorAll('button[data-si]').forEach(b=> b.addEventListener('click', e=> openTool({si:parseInt(e.target.getAttribute('data-si')), subIndex:parseInt(e.target.getAttribute('data-sub')), mode:'edit'}))); } if(panel==='users'){ let html='<h3>المستخدمون</h3>'; data.users.forEach((u,ui)=> html += '<div class=\"card\">'+u.username+' '+(u.isAdmin?'<span>(أدمن)</span>':'')+'<div>'+u.accountNumber+'</div><div>نقاط: '+(u.points||0)+'</div></div>'); content.innerHTML = html; } } document.querySelectorAll('button[data-panel]').forEach(b=> b.addEventListener('click', ()=> render(b.getAttribute('data-panel')))); render('dashboard'); window.openTool = function(opts){ const si=opts.si; const title = prompt('اسم الأداة'); if(!title) return; const isPaid = confirm('هل الأداة مدفوعة؟ OK = نعم'); const price = isPaid ? parseFloat(prompt('ادخل السعر (نقطة)'))||0 : 0; const content = prompt('محتوى الأداة'); const img = null; data.sections[si].subsections.push({ id:'sub'+Date.now(), name:title, paid:isPaid, price:price, content:content, image:img }); setData(data); toast('تم الإضافة'); render('sections'); }; document.getElementById('adminLogout').addEventListener('click', ()=>{ localStorage.removeItem('vee_session'); toast('تم تسجيل الخروج'); setTimeout(()=> location.href='login.html',700); }); }

  if(location.pathname.endsWith('code_explain.html')){ function detectLang(code){ const first = code.trim().split('\n')[0]; if(/\bdef\b|:\s*$/.test(first)) return 'python'; if(/<\/?(html|div|script)/i.test(code)) return 'html'; if(/function\s+|=>|console\.log/.test(code)) return 'javascript'; if(/\{[^}]*\}/.test(code) && /:\s*[^;]+;/.test(code)) return 'css'; return 'text'; } document.getElementById('explainBtn').addEventListener('click', async ()=>{ const code = document.getElementById('codeInput').value || ''; let lang = document.getElementById('codeLang').value || detectLang(code); const out = document.getElementById('explainOutput'); if(!code.trim()){ alert('ألصق الكود أولاً'); return; } try{ const resp = await askAI('اشرح هذا الكود:\\n'+code); out.innerText = resp; }catch(err){ const lines = code.split('\n'); const explanations = lines.map((ln,i)=> (i+1)+'. '+ln.trim()); out.innerText = 'شرح بدائي (محلي):\\n'+explanations.join('\\n'); } }); document.getElementById('voiceExplain').addEventListener('click', ()=>{ document.getElementById('explainBtn').click(); const text = document.getElementById('explainOutput').innerText || 'لا يوجد شرح'; if('speechSynthesis' in window){ const ut = new SpeechSynthesisUtterance(text); ut.lang='ar-SA'; speechSynthesis.speak(ut); } else alert('المتصفح لا يدعم النطق'); }); }

  // assistant UI
  const assistantBtn = document.getElementById('assistantBtn');
  if(assistantBtn){
    const panel = document.createElement('div'); panel.className='assistant-panel hidden'; panel.id='assistantPanel';
    panel.innerHTML = '<div class="assistant-header"><strong>Vee Assistant</strong><button id="assistantClose" class="btn">X</button></div><div class="assistant-messages" id="assistantMessages"></div><div class="assistant-input"><input id="assistantInput" placeholder="اسأل Vee..." /><button id="assistantSend" class="btn primary">إرسال</button></div>';
    document.body.appendChild(panel);
    document.getElementById('assistantClose').addEventListener('click', ()=> panel.classList.add('hidden'));
    assistantBtn.addEventListener('click', ()=> panel.classList.toggle('hidden'));
    const messages = document.getElementById('assistantMessages');
    function addMsg(text, who){ const d=document.createElement('div'); d.className='msg '+(who==='user'?'user':'bot'); d.innerText=text; messages.appendChild(d); messages.scrollTop=messages.scrollHeight; }
    document.getElementById('assistantSend').addEventListener('click', async ()=>{ const input=document.getElementById('assistantInput'); const text=input.value.trim(); if(!text) return; addMsg(text,'user'); input.value=''; try{ const reply = await askAI(text); addMsg(reply,'bot'); if('speechSynthesis' in window){ const ut=new SpeechSynthesisUtterance(reply); ut.lang='ar-SA'; speechSynthesis.speak(ut); } }catch(err){ addMsg('تعذر الاتصال بالمساعد.','bot'); } });
  }

  function addChat(who, text){ const area=document.getElementById('chatArea'); if(!area) return; const el=document.createElement('div'); el.className='msg '+(who==='user'?'user':'bot'); el.innerText=text; area.appendChild(el); area.scrollTop=area.scrollHeight; }

  async function askAI(message){
    if(window.callAIBridge){
      try{
        const res = await window.callAIBridge(message);
        if(res && res.reply) return res.reply;
        if(res && typeof res === 'string') return res;
        return JSON.stringify(res);
      }catch(err){ console.error('bridge error',err); }
    }
    if(message.toLowerCase().includes('ترمكس')) return 'لتعلم ترمكس: افتح القسم ثم اقرأ الأدوات.';
    if(message.toLowerCase().includes('شرح')) return 'يمكنك لصق الكود في صفحة شرح الأكواد وسأحاول شرحه.';
    return 'آسف، المساعد الحقيقي غير مكوّن حالياً. استخدم Bridge لربطه بـ OpenAI.';
  }
})();